# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nicolas P. Rougier
email: Nicolas.Rougier@inria.fr

url: ""
baseurl: "/perso/nrougier" # the subpath of your site, e.g. /blog


twitter_username: NPRougier
github_username:  rougier

# Build settings
markdown: kramdown

# Include future posts
future: true

# Jekyll scholar
gems: ['jekyll/scholar']

scholar:
  style: ./_bibliography/ieee-with-url.csl
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: rougier.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
